clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /root/.mix
      - deps
    volumes:
      - /data/cache/exchat:/cache

  build:
    image: bluerain/elixir-1.6-slim:mix-locals
    when:
      event: [push, tag, deployment]
    commands:
      - mix deps.get
      - MIX_ENV=prod mix release

  publish:
      image: plugins/docker
      when:
        event: [push, tag, deployment]
      repo: bluerain/exchat
      auto_tag: true
      dockerfile: Dockerfile
      secrets: [ docker_username, docker_password ]
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /root/.mix
      - deps
    volumes:
      - /data/cache/exchat:/cache
